DROP TABLE IF EXISTS code_barre;
DROP TABLE IF EXISTS recettes;
DROP TABLE IF EXISTS composition_journal_aliment;
DROP TABLE IF EXISTS aliment_plat;
DROP TABLE IF EXISTS aliments;
DROP TABLE IF EXISTS plats;
DROP TABLE IF EXISTS utilisateur_role;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS utilisateurs;