#CREATE DATABASE compteur_calories;

CREATE TABLE utilisateurs (
  id BIGSERIAL PRIMARY KEY,
  nom VARCHAR(50) UNIQUE NOT NULL,
  password VARCHAR(68) NOT NULL
);

CREATE TABLE roles (
  id BIGSERIAL PRIMARY KEY,
  nom VARCHAR(20) NOT NULL
);

CREATE TABLE utilisateur_role (
  user_id BIGSERIAL REFERENCES utilisateurs ON UPDATE CASCADE ON DELETE CASCADE,
  role_id BIGSERIAL REFERENCES roles ON UPDATE CASCADE ON DELETE CASCADE,
  PRIMARY KEY (user_id, role_id)
);

CREATE TABLE aliments (
    id BIGSERIAL PRIMARY KEY,
    nom VARCHAR(100) NOT NULL,
    user_id BIGSERIAL REFERENCES utilisateurs ON UPDATE CASCADE ON DELETE CASCADE,
    calories FLOAT(23) NOT NULL,
    unite VARCHAR(7) DEFAULT 'g',
    glucides FLOAT(23) NOT NULL,
    sucre FLOAT(23) DEFAULT 0,
    fibres FLOAT(23) DEFAULT 0,
    Mat_Gras FLOAT(23) NOT NULL,
    Mat_Gras_S FLOAT(23) DEFAULT 0,
    Mat_Gras_MI FLOAT(23) DEFAULT 0,
    Mat_Gras_PI FLOAT(23) DEFAULT 0,
    Mat_Gras_T FLOAT(23) DEFAULT 0,
    proteines FLOAT(23) NOT NULL,
    sel FLOAT(23) DEFAULT 0,
    cholesterol FLOAT(23) DEFAULT 0,
    pro_vit_A FLOAT(23) DEFAULT 0,
    vit_A FLOAT(23) DEFAULT 0,
    vit_B1 FLOAT(23) DEFAULT 0,
    vit_B2 FLOAT(23) DEFAULT 0,
    vit_B3 FLOAT(23) DEFAULT 0,
    vit_B5 FLOAT(23) DEFAULT 0,
    vit_B6 FLOAT(23) DEFAULT 0,
    vit_B8 FLOAT(23) DEFAULT 0,
    vit_B9 FLOAT(23) DEFAULT 0,
    vit_B11 FLOAT(23) DEFAULT 0,
    vit_B12 FLOAT(23) DEFAULT 0,
    vit_C FLOAT(23) DEFAULT 0,
    vit_D FLOAT(23) DEFAULT 0,
    vit_E FLOAT(23) DEFAULT 0,
    vit_K1 FLOAT(23) DEFAULT 0,
    vit_K2 FLOAT(23) DEFAULT 0,
    Ars FLOAT(23) DEFAULT 0,
    B FLOAT(23) DEFAULT 0,
    Ca FLOAT(23) DEFAULT 0,
    Cl FLOAT(23) DEFAULT 0,
    choline FLOAT(23) DEFAULT 0,
    Cr FLOAT(23) DEFAULT 0,
    Co FLOAT(23) DEFAULT 0,
    Cu FLOAT(23) DEFAULT 0,
    Fe FLOAT(23) DEFAULT 0,
    F FLOAT(23) DEFAULT 0,
    I FLOAT(23) DEFAULT 0,
    Mg FLOAT(23) DEFAULT 0,
    Mn FLOAT(23) DEFAULT 0,
    Mo FLOAT(23) DEFAULT 0,
    Na FLOAT(23) DEFAULT 0,
    P FLOAT(23) DEFAULT 0,
    K FLOAT(23) DEFAULT 0,
    Rb FLOAT(23) DEFAULT 0,
    SiO FLOAT(23) DEFAULT 0,
    S FLOAT(23) DEFAULT 0,
    Se FLOAT(23) DEFAULT 0,
    V FLOAT(23) DEFAULT 0,
    Sn FLOAT(23) DEFAULT 0,
    Zn FLOAT(23) DEFAULT 0,
    CONSTRAINT UC_Aliment UNIQUE (nom,user_id)
);

CREATE TABLE plats (
    id BIGSERIAL PRIMARY KEY,
    aliment_id BIGSERIAL REFERENCES aliments ON UPDATE CASCADE ON DELETE CASCADE,
    portions FLOAT(23)
);

CREATE TABLE recettes (
    plat_id BIGSERIAL REFERENCES plats ON UPDATE CASCADE ON DELETE RESTRICT,
    aliment_id BIGSERIAL REFERENCES aliments ON UPDATE CASCADE ON DELETE RESTRICT,
    quantite FLOAT(23),
    PRIMARY KEY (plat_id, aliment_id)
);

CREATE TABLE composition_journal_aliment (
    aliment_id BIGSERIAL REFERENCES aliments ON UPDATE CASCADE ON DELETE RESTRICT,
    user_id BIGSERIAL REFERENCES utilisateurs ON UPDATE CASCADE ON DELETE CASCADE,
    date_journal DATE,
    repas INTEGER,
    quantite FLOAT(23),
    PRIMARY KEY (aliment_id, user_id, date_journal, repas)
);

CREATE TABLE journal (
    user_id BIGSERIAL REFERENCES utilisateurs ON UPDATE CASCADE ON DELETE CASCADE,
    date_journal DATE,
    repas INTEGER,
    calories FLOAT(23),
    PRIMARY KEY (user_id, date_journal, repas)
);

CREATE TABLE code_barre (
    code_barre VARCHAR(13) PRIMARY KEY,
    aliment_id BIGSERIAL REFERENCES aliments ON UPDATE CASCADE ON DELETE CASCADE,
    marque VARCHAR(30)
);